### ISSUE TITLE
Plane in hangar

### ISSUE THREAD

**Issue by realhrky03** [TayMcKenzieNZ/CayoImprovements#1]
Hi and sorry for bothering You, is there a way to remove streamed plane texture that is located in hangar on the Island? Thanks in advance!

Here is an example:
https://i.imgur.com/4IDVSD6.png

**Comment by TayMcKenzieNZ** [comment]
Yes, anything is possible, however as a server owner or developer, you need to understand basic Lua, texture editing, and map editing. You can remove that plane using codewalker, and there are plenty of YouTube tutorials which you can find yourself.
