### ISSUE TITLE
Gas stations no longer explode in the entire map

### ISSUE THREAD

**Issue by SneakyAF** [TayMcKenzieNZ/CayoImprovements#4]
Took me a while to find that this is the resource responsible for such behavior but the explosions no longer happen when gas stations are demolished by a car for example.

The file responsible for this is **mads_no_exp_pumps.ytyp**

Any reason this is included? Is this a bug or a feature that it affects the entire map and not only the island?

**Comment by TayMcKenzieNZ** [comment]
File controls all gas pumps regardless of location. Removing this file sets them back to normal, allowing them to be exploded and messed with.
